name = "ellashaarshop"
compatibility_date = "2026-09-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "ELLAS_DB"
database_name = "ellashaarshop-db"
database_id = "816d1bdc-18f6-4762-a457-c9a3ac6e3dfb"
migrations_dir = "migrations"
